---
resources:
  - name: github-repo
    type: git
    source:
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
  - name: website
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: false
jobs:
  - name: spell-check
    plan:
      - get: github-repo
        trigger: true
      - task: check-spelling
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: tmaier/markdown-spellcheck
          inputs:
            - name: github-repo
          outputs:
            - name: generated-site
          run:
            dir: github-repo
            path: mdspell
            args:
              - --en-gb
              - --ignore-numbers
              - --report
              - '**/*.md'

  - name: deploy-website
    plan:
      - get: github-repo
        trigger: false
        passed:
          - spell-check
      - task: copy-content
        file: github-repo/ci/deploy-website/task.yml          
      - put: website
        params: 
          manifest: generated-site/manifest.yml
          path: generated-site