---
resources:
  - name: articles
    type: git
    source:
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
  - name: website
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: false
jobs:
  - name: spell-check
    plan:
      - get: articles
        trigger: true
      - task: check-spelling
        file: articles/ci/spell-check/task.yml
  - name: word-count
    plan:
      - get: articles
        trigger: true
      - task: count-words
        file: articles/ci/word-count/task.yml
  - name: validate-links
    plan:
      - get: articles
        trigger: true
      - task: link-validation
        file: articles/ci/link-validation/task.yml
  - name: voice-tone
    plan:
      - get: articles
        trigger: true
      - task: voice-tone-check
        file: articles/ci/voice-tone/task.yml
  - name: legal-check
    plan:
      - get: articles
        trigger: true
      - task: check-legal
        file: articles/ci/legal-check/task.yml
  - name: deploy-website
    plan:
      - get: articles
        trigger: false
        passed:
          - legal-check
          - spell-check
          - validate-links
          - word-count
          - voice-tone
      - task: copy-content
        file: articles/ci/deploy-website/task.yml          
      - put: website
        params: 
          manifest: generated-site/manifest.yml
          path: generated-site
