---
resources:
  - name: github-repo
    type: git
    source:
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
  - name: website-repo
    type: git
    source:
      branch: gh-pages
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
jobs:
  - name: deploy-website
    public: true
    plan:
      - get: github-repo
        trigger: false
      - get: website-repo
      - task: copy-content
        file: github-repo/ci/deploy-website/task.yml          
      - put: website-repo
        params: 
          repository: updated-website