---
resources:
  - name: fizzbuzzfeed-git
    type: git
    source:
      uri: https://github.com/armakuni/fizzbuzzfeed
      private_key: {{git-private-key}}
  - name: website
    type: git
    source:
      branch: gh-pages
      uri: https://github.com/armakuni/fizzbuzzfeed
      private_key: {{git-private-key}}
jobs:
  - name: job
    public: true
    plan:
      - get: fizzbuzzfeed-git
        trigger: true
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello, world!"]
      - put: website
        params: 
          repository: fizzbuzzfeed-git