---
resources:
  - name: github-repo
    type: git
    source:
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
  - name: website
    type: git
    source:
      branch: gh-pages
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
jobs:
  - name: job
    public: true
    plan:
      - get: github-repo
        trigger: true
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello, world!"]
      - put: website
        params: 
          repository: github-repo