---
resources:
  - name: github-repo
    type: git
    source:
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
  - name: website-repo
    type: git
    source:
      branch: gh-pages
      uri: git@github.com:armakuni/fizzbuzzfeed.git
      private_key: {{git-private-key}}
jobs:
  - name: deploy-website
    public: true
    plan:
      - get: github-repo
        trigger: false
      - get: website-repo
      - task: copy-content
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: bitnami/git, tag: 2.23.0 }
          inputs:
            - name: github-repo
            - name: website-repo
          outputs:
            - name: updated-website
          run:
            path: sh
            args: 
              - -exc 
              - |
                git config --global user.email "concourse@armakuni.com"
                git config --global user.name "Concourse"
                git clone website-repo updated-website
                cp -a github-repo/docs/* updated-website
                cd updated-website
                git add .
                git commit -m "Updating website" || true
      - put: website-repo
        params: 
          repository: updated-website